# Generated by Django 4.0.6 on 2022-09-15 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='writer',
        ),
        migrations.RemoveField(
            model_name='notificationtype',
            name='notification',
        ),
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='users.notificationtype'),
            preserve_default=False,
        ),
    ]
