# Generated by Django 4.0.6 on 2022-09-16 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_notification_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='category',
        ),
        migrations.DeleteModel(
            name='NotificationType',
        ),
    ]
