# Generated by Django 4.0.6 on 2022-09-17 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_notification_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='sender',
        ),
    ]
