# Generated by Django 4.0.6 on 2022-09-16 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_alter_adimage_ad'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
