# Generated by Django 4.0.8 on 2023-01-26 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_message_ad_alter_message_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='properties',
            field=models.ManyToManyField(blank=True, to='ads.propertyvalue'),
        ),
    ]
